default:
  theme: modern
  skin: light
  toolbar:
    - bold italic | forecolor backcolor | charmap link | preview fullscreen
  contextmenu: link inserttable
  plugins:
    - link
    - autolink
    - charmap
    - legacyoutput
    - paste
    - preview
    - table
    - textcolor
    - wordcount
    - colorpicker
    - lists
    - contextmenu
    - fullscreen